# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9f2cb326237c95eaf46afc296de301a5"
name = "review_app"
handle = "review-app-15"
application_url = "https://pads-codes-mood-lease.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://pads-codes-mood-lease.trycloudflare.com/auth/callback", "https://pads-codes-mood-lease.trycloudflare.com/auth/shopify/callback", "https://pads-codes-mood-lease.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
